name: Static analysis

on: [pull_request]

jobs:
  static-psalm-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix: # https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
        nextcloud: [ 'v21.0.0', 'v22.1.1', 'v23.0.2', 'dev-master' ]
        php: [ '7.3', '7.4', '8.0' ]
        exclude:
          - nextcloud: 'dev-master' 
            php: '7.3'
        include:
          - nextcloud: 'dev-master' 
            php: '8.1'
    name: Nextcloud ${{ matrix.nextcloud }} on PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2
          coverage: none
      - name: Remove PHP lockfile
        run: rm composer.lock
      - name: Install dependencies
        run: composer require --dev christophwurst/nextcloud:${{ matrix.nextcloud }}
      - name: Run coding standards check
        run: composer run -- psalm --php-version=${{ matrix.php }}
